server:
  port: 8500
spring:
  application:
    name: contacts-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/agenda?serviceTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto=update: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ContactsRealm
          jwk-set-uri: http://localhost:8080/realms/ContactsRealm/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
keycloak:
  clientId: login